AWSTemplateFormatVersion: "2010-09-09" 
Description: "References to created SecurityGroups"

Parameters:
  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  VpcId:
    Description: Select VPCID from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-DEV-ps-vpcid

Resources:
# EC2SecurityGroup01
  EC2SecurityGroup01:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: !Sub ${SystemName}-${Env}-EC2SecurityGroup01
        GroupName: !Sub ${SystemName}-${Env}-EC2SecurityGroup01
        VpcId: !Ref VpcId
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        Tags:
          - Key: Name
            Value: !Sub ${SystemName}-${Env}-EC2SecurityGroup01

        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # EC2SecurityGroup02
  EC2SecurityGroup02:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: !Sub ${SystemName}-${Env}-EC2SecurityGroup02
        GroupName: !Sub ${SystemName}-${Env}-EC2SecurityGroup02
        VpcId: !Ref VpcId
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

        Tags:
          - Key: Name
            Value: !Sub ${SystemName}-${Env}-EC2SecurityGroup02

        SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0        

# ELBIngressGroup
  ELBIngressGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELBingressgroup
      GroupName: !Sub ${SystemName}-${Env}-ELBIngressGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      Tags:
          - Key: Name
            Value: !Sub ${SystemName}-${Env}-ELBIngressGroup

# DBSecurityGroup01
  DBSecurityGroup01:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${SystemName}-${Env}-DBSecurityGroup01
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !Ref EC2SecurityGroup01
      Tags:
          - Key: Name
            Value: !Sub ${SystemName}-${Env}-DBSecurityGroup01

Outputs:
  EC2SecurityGroup01:
    Description: The security group ID to use for public web servers
    Value: !Ref EC2SecurityGroup01
    Export:
      Name: EC2SecurityGroup01

  EC2SecurityGroup02:
    Description: The security group ID to use for public web servers
    Value: !Ref EC2SecurityGroup02
    Export:
      Name: EC2SecurityGroup02

  ELBIngressGroup:
    Description: The security group ID to use for public web servers
    Value: !Ref ELBIngressGroup
    Export:
      Name: ELBIngressGroup

  DBSecurityGroup01:
    Description: The security group ID to use for public web servers
    Value: !Ref DBSecurityGroup01
    Export:
      Name: DBSecurityGroup01