AWSTemplateFormatVersion: "2010-09-09"
Description: References to created CW IAM.

Parameters:
  env:
    Description: hon, dev
    Type: String
    Default: dev

  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

Resources:
  # CodeWatchAgentを実行できるIAMRole
  FormEC2IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      RoleName: !Sub ${SystemName}-${env}-CloudWatchAgentServerPolicy
      # EC2に適した管理ポリシーのARNをここに列挙する。
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

      Tags: 
        - Key: Name
          Value: CloudWatchAgentServerPolicyRole
