Description: References to created IGW, NatGW, AZ, Subnet, 

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

  VpcId:
    Description: Select VPCID from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-DEV-ps-vpcid

  VpcCidr:
    Description: Select VPCCIDR from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-DEV-ps-vpccidr

  GenkoSubnet1CIDR:
    Description: GenkoPrivateSubnet1CIDR
    Type: String
    Default: 10.0.0.0/24
  
  GenkoSubnet2CIDR:
    Description: GenkoPrivateSubnet2CIDR
    Type: String
    Default: 10.0.1.0/24
  
  APISubnet1CIDR:
    Description: APIPrivateSubnet1CIDR
    Type: String
    Default: 10.0.2.0/24
  
  APISubnet2CIDR:
    Description: APIPrivateSubnet2CIDR
    Type: String
    Default: 10.0.3.0/24

  DBSubnet1CIDR:
    Description: DBSubnet1CIDR
    Type: String
    Default: 10.0.4.0/24
  
  DBSubnet2CIDR:
    Description: DBSubnet2CIDR
    Type: String
    Default: 10.0.5.0/24

  PrivateSubnet1CIDR:
    Description: PrivateSubnet1CIDR
    Type: String
    Default: 10.0.6.0/24

  PrivateSubnet2CIDR:
    Description: PrivateSubnet1CIDR
    Type: String
    Default: 10.0.7.0/24

  PrivateSubnet3CIDR:
    Description: PrivateSubnet3CIDR
    Type: String
    Default: 10.0.8.0/24

  PrivateSubnet4CIDR:
    Description: PrivateSubnet4CIDR
    Type: String
    Default: 10.0.9.0/24

  PrivateSubnet5CIDR:
    Description: PrivateSubnet5CIDR
    Type: String
    Default: 10.0.10.0/24

Resources:
# GenkoSubnet1
  GenkoSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref GenkoSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-Genko-PrivateSubnet-01

# GenkoSubnet2
  GenkoSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: !Ref GenkoSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-Genko-Private-Subnet-02

# APISubnet1
  APISubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref APISubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-API-Private-Subnet-01

# APISubnet2
  APISubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 2, !GetAZs  '' ]
      CidrBlock: !Ref APISubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-API-Private-Subnet-02

# DBSubnet1
  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref DBSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-DB-Private-Subnet-01

# DBSubnet2
  DBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref DBSubnet2CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-DB-Private-Subnet-02

# DBSubnetGroup
  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetgroup
      DBSubnetGroupName: DBSubnetgroup
      SubnetIds:
       - !Ref GenkoSubnet1
       - !Ref GenkoSubnet2
      Tags: 
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-DB-Private-Subnetgroup

# PrivateSubnet1
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateSubnet-alb-01

# PrivateSubnet2
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateSubnet-alb-02

# PrivateSubnet3
  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet3CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateSubnet-alb-03

# PrivateSubnet4
  PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet4CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateSubnet-alb-04

# PrivateSubnet5
  PrivateSubnet5:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcId
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet5CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateSubnet-alb-05

#------------------------------------------
#InternetGateway,Route
#------------------------------------------

# InternetGateway 
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref SystemName

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId 

#RouteTable
  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${Env}-PrivateRouteTable

#Route
  PrivateRoute:
    Type: "AWS::EC2::Route"
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

##-----------------------------------------------
#SubnetsAssociation 
##-----------------------------------------------
  GenkoSubnetRouteTableAssoc01:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref GenkoSubnet1

  GenkoSubnetRouteTableAssoc02:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref GenkoSubnet2

  APISubnetRouteTableAssoc01:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref APISubnet1

  APISubnetRouteTableAssoc02:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref APISubnet2

  DBSubnetRouteTableAssoc01:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref DBSubnet1

  DBSubnetRouteTableAssoc02:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref DBSubnet2

  PrivateSubnetRouteTableAssoc01:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  PrivateSubnetRouteTableAssoc02:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

  PrivateSubnetRouteTableAssoc03:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet3

  PrivateSubnetRouteTableAssoc04:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet4

  PrivateSubnetRouteTableAssoc05:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet5


#-------------------------------------------------------
#-------------------------------------------------------

Outputs:
  GenkoSubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref GenkoSubnet1, !Ref GenkoSubnet2 ]]

  APISubnets:
    Description: A list of the public subnets
    Value: !Join [ ",", [ !Ref APISubnet1, !Ref APISubnet2 ]]

  PrivateSubnets:
    Description: A list of the private subnets
    Value: !Join [ ",", [ !Ref PrivateSubnet1, !Ref PrivateSubnet2, !Ref PrivateSubnet3, !Ref PrivateSubnet4, !Ref PrivateSubnet5 ]]

  GenkoSubnet1:
    Description: Output of Genko subnet 1
    Value: !Ref GenkoSubnet1
    Export:
      Name: GenkoSubnet1
        
  GenkoSubnet2:
    Description: Output of Genko subnet 2
    Value: !Ref GenkoSubnet2
    Export:
      Name: GenkoSubnet2

  APISubnet1:
    Description: Output of API subnet 1
    Value: !Ref APISubnet1
    Export:
      Name: APISubnet1

  APISubnet2:
    Description: Output of API subnet 2
    Value: !Ref APISubnet2
    Export:
      Name: APISubnet2

  DBSubnet1:
    Description: Output of DB subnet 1
    Value: !Ref DBSubnet1
    Export:
      Name: DBSubnet1

  DBSubnet2:
    Description: Output of DB subnet 2
    Value: !Ref DBSubnet2
    Export:
      Name: DBSubnet2

  PrivateSubnet1:
    Description: Output of Private subnet 1
    Value: !Ref PrivateSubnet1
    Export:
      Name: PrivateSubnet1

  PrivateSubnet2:
    Description: Output of Private subnet 2
    Value: !Ref PrivateSubnet2
    Export:
      Name: PrivateSubnet2

  PrivateSubnet3:
    Description: Output of Private subnet 3
    Value: !Ref PrivateSubnet3
    Export:
      Name: PrivateSubnet3

  PrivateSubnet4:
    Description: Output of Private subnet 4
    Value: !Ref PrivateSubnet4
    Export:
      Name: PrivateSubnet4

  PrivateSubnet5:
    Description: Output of Private subnet 5
    Value: !Ref PrivateSubnet5
    Export:
      Name: PrivateSubnet5

  DBSubnetGroup:
    Description: Subnet for DB
    Value: !Ref DBSubnetGroup
    Export:
      Name: DBSubnetGroup