Description: Template to be added to the parameter store. 

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample
  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

Resources:
#After VPC creation.
#-------------------------------------------------
  VpcId:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-vpcid
      Description: Create VPCID in SSM Parameter Store.
      Type: String
      Value: vpc-047fee79c7d2ee47d

  VpcCidr:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-vpccidr
      Description: Create VPC Cider in SSM Parameter Store.
      Type: String
      Value: 10.0.0.0/16
#-------------------------------------------------

#After IGW, AZ, Subnet, Route, RouteTable creation.
#--------------------------------------------------
  PrivateRoutetableid:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-routetableid-private
      Description: Create a private routetableid for the VPC in the SSM Parameter Store.
      Type: String
      Value: rtb-0d2ed580bd02a4925 

  GenkoSubnetids:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-subnetids-genko
      Description: Create a genko subnetids for the VPC in the SSM Parameter Store.
      Type: StringList
      Value: subnet-04a6341245e5db30e, subnet-088a52aa01bf7ef2a

  APISubnetids:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-subnetids-api
      Description: Create a API subnetids for the VPC in the SSM Parameter Store.
      Type: StringList
      Value: subnet-0b5cd7a62deaecc8a, subnet-0eced4c31d221a9f0

  ALBPrivateSubnetids:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-subnetids-privatealb
      Description: Create a Private ALB subnetids for the VPC in the SSM Parameter Store.
      Type: StringList
      Value: subnet-0f6402c3d915a33fa, subnet-0e36a3142f6020365, subnet-0d962a0390ab78e5e, subnet-02bc828d54dbe4e66, subnet-0914606276afcd50e

#--------------------------------------------------      



  # Ec2Image:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ec2-ImageId
  #     Description: Create EC2 image in SSM Parameter Store.
  #     Type: String
  #     DataType: aws:ec2:image
  #     Value: ami-0b7546e839d7ace12



  # PrivateSubnetid2:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ps-subnetid2-private
  #     Description: Create a private subnetids for the VPC in the SSM Parameter Store.
  #     Type: String
  #     Value: 10.0.3.0/24

  # PublicRoutetableId:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ps-routetableid-private
  #     Description: Create a private routetableid for the VPC in the SSM Parameter Store.
  #     Type: String
  #     Value: rtb-0f72bcf39e1657cf9

