Description: Template to be added to the parameter store. 

AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample
  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

Resources:
  VpcId:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-vpcid
      Description: Create VPCID in SSM Parameter Store.
      Type: String
      Value: vpc-047fee79c7d2ee47d

  VpcCidr:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-vpccidr
      Description: Create VPC Cider in SSM Parameter Store.
      Type: String
      Value: 10.0.0.0/16

  # Ec2Image:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ec2-ImageId
  #     Description: Create EC2 image in SSM Parameter Store.
  #     Type: String
  #     DataType: aws:ec2:image
  #     Value: ami-0b7546e839d7ace12

  PrivateRoutetableid:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ps-routetableid
      Description: Create a private routetableid for the VPC in the SSM Parameter Store.
      Type: String
      Value: rtb-0911fa4697b87f6e0

  # PrivateSubnetid1:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ps-subnetid1-private
  #     Description: Create a private subnetids for the VPC in the SSM Parameter Store.
  #     Type: String
  #     Value: 10.0.2.0/24

  # PrivateSubnetid2:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ps-subnetid2-private
  #     Description: Create a private subnetids for the VPC in the SSM Parameter Store.
  #     Type: String
  #     Value: 10.0.3.0/24

  # PublicRoutetableId:
  #   Type: AWS::SSM::Parameter
  #   Properties: 
  #     Name: !Sub ${SystemName}-${Env}-ps-routetableid-private
  #     Description: Create a private routetableid for the VPC in the SSM Parameter Store.
  #     Type: String
  #     Value: rtb-0f72bcf39e1657cf9

