Description: Template for creating an ECS task.

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

  ECSTaskCPUUnit:
    AllowedValues: [256, 512, 1024, 2048, 4096]
    Type: String
    Default: 256

  ECSTaskMemory:
    AllowedValues: [256, 512, 1024, 2048, 4096]
    Type: String
    Default: 512

  ECSTaskExecutionRole:
    Type: String
    Default: arn:aws:iam::448678968380:role/sample-ECSTaskExecutionRolePolicy

  ECSImageName:
    Type: String
    Default: ECSImage

  ECSCluster:
    Description: Select ECSCluster from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-DEV-ecs-cluster

  #ECSTaskDesiredCount
  ECSTaskDesiredCount:
    Type: Number
    Default: 1

  TargetGroup01:
    Description: Select ALB targetgroup01 from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-dev-alb-targetgroup01

  ecssecuritygroups:
    Description: Select ECS SecurityGroups from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: sample-DEV-ecs-securitygroups
  
  #ECSSubnet1
  ECSSubnetId1:
    Description: 'ECS Subnet 1st'
    Type: AWS::EC2::Subnet::Id

  #ECSSubnet2
  ECSSubnetId2:
    Description: 'ECS Subnet 2st'
    Type: AWS::EC2::Subnet::Id

# ------------------------------------------------------------#
#  ECS TaskDefinition
# ------------------------------------------------------------#
Resources:
  ECSTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Cpu: !Ref ECSTaskCPUUnit
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      Family: !Sub ${SystemName}-ECSTask
      Memory: !Ref ECSTaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE

      ContainerDefinitions:
        - Name: !Sub ${SystemName}-ECSContainer
          Image: !Ref ECSImageName
          MemoryReservation: 128
          PortMappings:
            - HostPort: 80
              Protocol: tcp
              ContainerPort: 80

  # ------------------------------------------------------------#
  #  ECS Service
  # ------------------------------------------------------------#

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      DeploymentController:
        Type: CODE_DEPLOY
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup01
          ContainerPort: 80
          ContainerName: !Sub ${SystemName}-ECSContainer
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-0808c7427be0e2f36
            - sg-0eb56f0cb840917d8
          Subnets:
            - !Ref ECSSubnetId1
            - !Ref ECSSubnetId2

      ServiceName: !Sub ${SystemName}-ECSService
      TaskDefinition: !Ref ECSTaskDefinition

# --------------------------------------------------------------
# Parameter Store
# --------------------------------------------------------------

  ecstaskdefinition:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ECS-TaskDefinition
      Description: Create ECS TaskDefinition in SSM Parameter Store.
      Type: String
      Value: !Ref ECSTaskDefinition

  ecsservice:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ECS-Service
      Description: Create ECS TaskDefinition in SSM Parameter Store.
      Type: String
      Value: !Ref ECSService
