Description: Template for creating an ECS cluster.

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

Resources:  
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - FARGATE
      ClusterName: EcsCluster
      ClusterSettings: 
        - Name : containerInsights 
          Value: enabled
      Tags: 
        - Key  : Name
          Value: !Sub ${SystemName}-${Env}-ecs-cluster

  ecscluster:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-ecs-cluster
      Description: Create ecs cluster in SSM Parameter Store.
      Type: String
      Value: !Ref EcsCluster
