AWSTemplateFormatVersion: "2010-09-09"
Description: References to created EC2, EBS

Parameters:
  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  # EC2のキーペアの名前を定義し、スタック作成時にコンソールで指定する
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "sample-DEV"
  
  ImageId: 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: sample-DEV-ec2-ImageId

Resources:
#EC2
  Rubyweb1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      AvailabilityZone: "ap-northeast-1a"
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnet1
          GroupSet:
           - !ImportValue EC2SecurityGroup01
      # SubnetId: !ImportValue PublicSubnet1
      # SecurityGroupIds:
      #   - !ImportValue EC2SecurityGroup01
      Tags:
          - Key: Name
            Value: sample-ec2-Rubyweb1
# ebs
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 8

  Rubyweb2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      AvailabilityZone: "ap-northeast-1c"
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnet2
          GroupSet:
           - !ImportValue EC2SecurityGroup02
      # SubnetId: !ImportValue PublicSubnet2
      # SecurityGroupIds:
      #   - !ImportValue EC2SecurityGroup02
      Tags:
          - Key: Name
            Value: sample-ec2-Rubyweb2
# ebs
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 8

Outputs:
  Rubyweb1:
    Description: Rubyweb1
    Value: !Ref Rubyweb1
    Export:
      Name: Rubyweb1

  Rubyweb2:
    Description: Rubyweb2
    Value: !Ref Rubyweb2
    Export:
      Name: Rubyweb2
