AWSTemplateFormatVersion: "2010-09-09"
Description: References to created EC2, EBS

Parameters:
  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  ## EC2のキーペアの名前を定義し、スタック作成時にコンソールで指定を行なう。
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: "sample-DEV"
  
  ImageId: 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: sample-DEV-ec2-ImageId

Resources:
#EC2
  jumpserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      AvailabilityZone: "ap-northeast-1a"
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue GenkoSubnet1
          GroupSet:
           - !ImportValue EC2SecurityGroup01
      # SubnetId: !ImportValue PublicSubnet1
      # SecurityGroupIds:
      #   - !ImportValue EC2SecurityGroup01
      Tags:
          - Key: Name
            Value: sample-ec2-jumpserver
# ebs
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 8

# --------------------------------------------------------------
# Parameter Store
# --------------------------------------------------------------

  JumpServer:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-JumpServer-ID
      Description: Create JumpServer in SSM Parameter Store.
      Type: String
      Value: !Ref jumpserver

# --------------------------------------------------------------
# Outputs
# --------------------------------------------------------------

Outputs:
  jumpserver:
    Description: jumpserver
    Value: !Ref jumpserver
    Export:
      Name: jumpserver

  # Rubyweb2:
  #   Description: Rubyweb2
  #   Value: !Ref Rubyweb2
  #   Export:
  #     Name: Rubyweb2
