AWSTemplateFormatVersion: "2010-09-09"
Description: References to created ELB

Parameters:
  Env:
    Description: hon, dev
    Type: String
    Default: dev

  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  VpcId:
    Description: Select VPCID from SSM Prameter Store.
    Type: AWS::SSM::Parameter::Value<String>
    Default: sample-DEV-ps-vpcid

  GenkoSubnetids: 
    Description: Create a genko subnetids for the VPC in the SSM Parameter Store.
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: sample-DEV-ps-subnetids-genko

Resources:
# # ALBS3Bucket
#   albs3bucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Sub ${SystemName}-${Env}-alb-log



## ---------------------------
## ２つのターゲットグループ
#  TargetGroup01
  sampleTargetGroup01:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VpcId
      Name: sample-TargetGroup01
      Protocol: HTTP
      Port: 80
      TargetType: ip
      
#  TargetGroup02
  sampleTargetGroup02:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VpcId
      Name: sample-TargetGroup02
      Protocol: HTTP
      Port: 8080
      TargetType: ip

# ALB 
  sampleALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: sample-dev-ALB
      Tags:
        - Key: Name
          Value: sample-ALB
      Scheme: "internet-facing"
      LoadBalancerAttributes:
        - Key: "deletion_protection.enabled"
          Value: false
        - Key: "idle_timeout.timeout_seconds"
          Value: 60
        # - Key: "access_logs.s3.enabled"
        #   Value: true
        # - Key: "access_logs.s3.bucket"
        #   Value: !Sub "albs3bucket"
        # - Key: access_logs.s3.prefix
        #   Value: "dev"
      SecurityGroups:
      - !ImportValue ELBIngressGroup
      Subnets: !Ref GenkoSubnetids

      # Tags: 
      #   - Key: Name
      #     Value: sampleTargetGroup

      # TargetGroupAttributes: 
      #   - Key: "deregistration_delay.timeout_seconds"
      #     Value: 300
      #   - Key: "stickiness.enabled"
      #     Value: false
      #   - Key: "stickiness.type"
      #     Value: lb_cookie
      #   - Key: "stickiness.lb_cookie.duration_seconds"
      #     Value: 86400

      # Targets: 
      #   - Id: !ImportValue Rubyweb1
      #     Port: 80
      #   - Id: !ImportValue Rubyweb2
      #     Port: 80

##--------------------------------------
## １つのリスナールール作成。
# albListener 
  sampleALBListener1:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref sampleTargetGroup01
          Type: forward
      LoadBalancerArn: !Ref sampleALB
      Port: 80
      Protocol: HTTP

# albListener
  sampleALBListener2:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - TargetGroupArn: !Ref sampleTargetGroup02
          Type: forward
      LoadBalancerArn: !Ref sampleALB
      Port: 8080
      Protocol: HTTP


# --------------------------------------------------------------
# Parameter Store
# --------------------------------------------------------------
  SampleALBListener1:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-alb-listener1
      Description: Create sample ALBListener1 in SSM Parameter Store.
      Type: String
      Value: !Ref sampleALBListener1

  SampleALBListener2:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-alb-listener2
      Description: Create sample ALBListener2 in SSM Parameter Store.
      Type: String
      Value: !Ref sampleALBListener2

  samplealb:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-alb
      Description: Create sample ALB in SSM Parameter Store.
      Type: String
      Value: !Ref sampleALB

  sampletargetgroup01:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-alb-targetgroup01
      Description: Create ALB TargetGroup01 in SSM Parameter Store.
      Type: String
      Value: !Ref sampleTargetGroup01

  sampletargetgroup02:
    Type: AWS::SSM::Parameter
    Properties: 
      Name: !Sub ${SystemName}-${Env}-alb-targetgroup02
      Description: Create ALB TargetGroup02 in SSM Parameter Store.
      Type: String
      Value: !Ref sampleTargetGroup02


