AWSTemplateFormatVersion: '2010-09-09'
Description: Create CodeDeploy IAM Role

Parameters:
  SystemName:
    Description: Enter SystemName
    Type: String
    Default: sample

  Env:
    Description: HON, DEV
    Type: String
    Default: DEV

Resources:
  #  BlueGreen CodeDeploy Role
  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${Env}-codedeploy-iamrole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS

<<<<<<< HEAD
        
=======

        # CodeBuild
>>>>>>> 9abaf810c2fae769ae6864d200caa19c674c2a6c
